In [146]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model

In [147]:
model =load_model("model.h5")

In [148]:
import pickle
with open("C:\ds\churn_modelling\label_encoder_gender.pkl",'rb') as file:
    label_encoder_gener=pickle.load(file)
with open("C:\ds\churn_modelling\onehot_encoder_geo.pkl",'rb') as file:
    onehot_encoder_geo=pickle.load(file)
with open("C:\ds\churn_modelling\scaler.pkl",'rb') as file:
    scaler=pickle.load(file)

In [149]:
input_data = {
'CreditScore': 0,
'Geography': 'France',
'Gender': 'Male',
'Age': 40,
'Tenure': 3,
'Balance': 0,
'NumOfProducts': 0,
'HasCrCard': 1,
'IsActiveMember': 1,
'EstimatedSalary': 5
}

In [150]:
df=pd.DataFrame([input_data],columns=input_data.keys())

In [151]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0,France,Male,40,3,0,0,1,1,5

In [152]:
df['Gender']=label_encoder_gener.transform(df['Gender'])

In [153]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0,France,1,40,3,0,0,1,1,5

In [154]:
geo_df = onehot_encoder_geo.transform(df[['Geography']]).toarray()
geo_df=pd.DataFrame(geo_df,columns=onehot_encoder_geo.get_feature_names_out())

In [155]:
geo_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [156]:
df=pd.concat([df,geo_df],axis=1)
df.drop(columns=['Geography'],axis=1,inplace=True)

In [157]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,0,1,40,3,0,0,1,1,5,1.0,0.0,0.0

In [158]:
df=pd.DataFrame(scaler.transform(df),columns=scaler.get_feature_names_out())

In [159]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,-6.731607,0.912849,0.102135,-0.694636,-1.225414,-2.625349,0.642621,0.969531,-1.745496,1.001067,-0.582482,-0.573039

In [160]:
y_predict=model.predict(df)

1/1 [==============================] - 0s 118ms/step

In [161]:
y_predict[0][0]

0.5838559

In [162]:
if(y_predict[0][0]>0.5):
    print("customer exited the bank")
    
else : print('Customer doesnot exited the bank')

customer exited the bank